name: Build and push container

on:
    workflow_dispatch:
    push:
        branches: 
            - "main"

env:
    DOCKER_IMAGE_NAME: "microscale-users"

jobs:
    build-and-push:
        name: Build and push
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            
            - name: Log in to the container registry
              uses: docker/login-action@v3
              with:
                registry: ${{ vars.AZURE_CONTAINER_REGISTRY_URL }}
                username: ${{ vars.AZURE_CONTAINER_REGISTRY_USERNAME }}
                password: ${{ vars.AZURE_CONTAINER_REGISTRY_PASSWORD }}
            
            - name: Prepare image metadata
              id: image-metadata
              uses: docker/metadata-action@v5
              with:
                images: ${{ vars.AZURE_CONTAINER_REGISTRY_URL }}/${{ vars.DOCKER_IMAGE_NAME }}

            - name: Build, tag, and push the container
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: ${{ steps.image-metadata.outputs.tags }}
